const contacts = [
  { id:"crmmarketplace", kind:"партнёр", name:"Union‑Marketplace News", handle:"@eaglessias", url:"https://t.me/s/crmmarketplace/2735", audience:"Селлеры WB, Ozon, Яндекс Маркет и Мегамаркет", why:"Канал публикует новости и уже размещает материалы о визуале карточек.", offer:"Гостевой разбор одного первого кадра с честной границей данных.", format:"партнёрство", score:10, evidence:"Контакт виден в описании канала; проверено 07.08.2026.", draft:"Здравствуйте. Вижу, что вы публикуете прикладные материалы для селлеров. Предлагаю не рекламный пост, а короткий разбор одного первого кадра: что видно в выдаче, какую гипотезу можно проверить и какие данные нужны до вывода о CTR. Если формат подходит, пришлю пример и структуру." },
  { id:"alliance", kind:"партнёр", name:"Канал поставщиков WB — Альянс", handle:"@Snezha_91", url:"https://t.me/s/wildberries_marketplace?before=1147", audience:"Поставщики и продавцы Wildberries", why:"У канала есть публичный контакт по рекламе и активный чат селлеров.", offer:"Экспертный пост или эфир «первый кадр без обещаний продаж».", format:"партнёрство", score:9, evidence:"Публичный контакт по рекламе; проверено 07.08.2026.", draft:"Здравствуйте. Для аудитории селлеров могу подготовить полезный материал без громких обещаний: как отделить проблему главного кадра от цены, отзывов и рекламы и какой A/B‑тест запускать первым. Сначала пришлю тезисы и пример визуала; публикация только после согласования." },
  { id:"seller_support", kind:"сообщество", name:"Чат поддержки поставщиков Wildberries", handle:"@info_mpgroupbot", url:"https://t.me/sellers_wildberries", audience:"Селлеры Wildberries, поддержка и обучение", why:"В описании прямо указан контакт для сотрудничества.", offer:"Открытый мини‑разбор одного разрешённого SKU или чек‑лист.", format:"партнёрство", score:9, evidence:"Контакт сотрудничества в публичном описании; проверено 07.08.2026.", draft:"Здравствуйте. Хочу предложить формат, полезный чату: один разрешённый SKU, два варианта главного кадра и список условий честного теста. Без массовой рекламы и без гарантии продаж. Подскажите, допустим ли такой экспертный материал и как его согласовать?" },
  { id:"kmedia", kind:"площадка", name:"K.MEDIA · подборки WB", handle:"@nika_kravtc", url:"https://t.me/s/wildberries_reklama_wb", audience:"Покупательские каналы, стилистические подборки и бренды", why:"Есть открытые менеджеры и регулярные тематические подборки товаров.", offer:"Партнёрский A/B‑кадр для одного бренда перед размещением в подборке.", format:"партнёрство", score:8, evidence:"Менеджеры и форматы размещений видны публично; проверено 07.08.2026.", draft:"Здравствуйте. В ваших подборках товару особенно важен первый визуальный контакт. Могу предложить совместный тест: для одного участника подготовить два разрешённых кадра и до размещения выбрать, какой яснее считывается в ленте. Если интересно, пришлю примеры и границы формата." },
  { id:"tcatca", kind:"бренд", name:"Tca‑Tca cashmere", handle:"@tcatcamanager", url:"https://t.me/s/tcatca/2917", audience:"Покупатели российского бренда кашемира и шёлка", why:"Небольшой бренд регулярно показывает фактуру, цвет и короткие видео продукта.", offer:"Три кадра одного изделия: силуэт, движение, фактура.", format:"личное сообщение", score:11, evidence:"Менеджер публично указан в описании канала; короткие ролики 12–14 сек видны в ленте.", draft:"Здравствуйте. Посмотрел канал Tca‑Tca: материал и цвет уже звучат сильно. Я бы протестировал для одного изделия короткую связку из трёх кадров — силуэт, движение и макро фактуры — сохранив реальный цвет и конструкцию. Если актуально, пришлите одну модель и текущие исходники; покажу направление до большой серии." },
  { id:"job_design", kind:"вакансия", name:"РАБОТА. ДИЗАЙН ИНТЕРЬЕРА · M4", handle:"@FinoarteHR", url:"https://t.me/s/job_design", audience:"Интерьерные бюро и визуализаторы", why:"В публичной вакансии отдельно запрошено портфолио AI‑визуализаций.", offer:"Релевантное портфолио и тестовая визуальная концепция по ТЗ.", format:"отклик", score:12, evidence:"Открытая вакансия с прямым контактом; перед откликом проверить, что позиция ещё актуальна.", draft:"Здравствуйте. Увидел вакансию M4 с задачей AI‑визуализаций для градостроительной концепции. У меня есть портфолио коммерческих визуальных серий и процесс контроля фактуры, геометрии и единого стиля. Готов прислать релевантную подборку и обсудить один тестовый кадр по вашему ТЗ. Подскажите, вакансия ещё открыта?" },
  { id:"designwork", kind:"площадка", name:"Вакансии для дизайнера", handle:"@Design_rabota_vacansy_bot", url:"https://t.me/s/designwork_vacansii/6644", audience:"Заказчики и специалисты дизайна", why:"Площадка принимает вакансии и резюме через публичный бот.", offer:"Размещение узкого предложения: AI‑визуал для e‑commerce и обложек.", format:"партнёрство", score:8, evidence:"Публичный бот размещений виден в описании канала.", draft:"Здравствуйте. Хочу уточнить формат размещения узкого портфолио: AI‑визуал для карточек товара, обложек и бренд‑серий с ручным контролем соответствия продукту. Пришлю короткий текст и ссылку на работы; ничего не публиковать без вашего подтверждения." },
  { id:"podcastjob", kind:"партнёр", name:"Подкастинг: CV · Вакансии · Ивенты", handle:"@gumadoina", url:"https://t.me/s/podcastjob?before=371", audience:"Авторы и продюсеры подкастов", why:"Канал объединяет вакансии, резюме и события подкаст‑рынка.", offer:"Разбор обложки в маленьком квадрате или три key‑visual направления.", format:"партнёрство", score:10, evidence:"Публичный контакт указан в описании; проверено 07.08.2026.", draft:"Здравствуйте. Для авторов подкастов могу предложить практический формат: разбор одной обложки в размере плеера и три разных направления центрального образа. Это не продажа в лоб, а полезный материал с примерами. Если подходит аудитории, пришлю структуру." },
  { id:"podcasts", kind:"медиа", name:"Podcasts.ru", handle:"editor@podcasts.ru", url:"https://t.me/s/podcasts/1850", audience:"Русскоязычные подкастеры и студии", why:"Профильное медиа публикует кейсы, статистику и сотрудничества.", offer:"Гостевая заметка о визуальной системе подкаста и проверке thumbnail.", format:"партнёрство", score:9, evidence:"Публичная редакционная почта видна в описании канала.", draft:"Здравствуйте. Предлагаю прикладную заметку для авторов: как проверить обложку в маленьком квадрате, собрать три визуальных направления и не потерять узнаваемость в серии выпусков. Без копирования чужих кейсов; могу приложить собственные примеры WISE / FRAME. Подскажите, интересен ли редакции такой материал?" },
  { id:"marketingaudio", kind:"подкаст", name:"Маркетинг и реальность", handle:"@fenixeales", url:"https://t.me/s/marketingaudio/1493", audience:"Предприниматели, специалисты marketing, PR и брендинга", why:"Автор открыт к участию, партнёрствам и бренд‑материалам.", offer:"Совместный выпуск/короткая рубрика о visual performance без магических обещаний.", format:"партнёрство", score:10, evidence:"Публичные контакты автора и спонсорства указаны в канале.", draft:"Александр, здравствуйте. Предлагаю тему без обещаний «картинка поднимет продажи»: как связать главный кадр, CTR, конверсию и рекламный расход и где визуальный специалист обязан остановить вывод. Могу подготовить три наглядных примера и короткую бесплатную диагностику для слушателей. Если тема подходит, пришлю план на одну страницу." },
  { id:"psy_podcast", kind:"подкаст", name:"Психология с Александрой Яковлевой", handle:"@Psycho_AY", url:"https://t.me/s/psy_with_yakovleva/1217", audience:"Слушатели экспертного психологического подкаста", why:"Канал публикует видео/аудио и имеет открытый контакт сотрудничества.", offer:"Обновление системы обложек и анонсов без изменения содержания проекта.", format:"партнёрство", score:8, evidence:"Контакт сотрудничества публично указан; проверено 07.08.2026.", draft:"Здравствуйте. У подкаста уже сильная экспертная основа. Могу предложить не «ребрендинг ради ребрендинга», а тест: три обложки одной темы, проверенные в маленьком квадрате, и единая система анонсов. Если задача актуальна, пришлю короткий визуальный разбор текущей подачи." },
  { id:"tobiz", kind:"площадка", name:"Ту Биз · товарка и поставщики", handle:"@tobizadmin2", url:"https://t.me/s/opt_tobiz?before=36576", audience:"Производители, поставщики и продавцы товаров", why:"Канал публикует товары и имеет открытый рекламный контакт.", offer:"Рубрика «один товар — один первый кадр» с разрешённым участником.", format:"партнёрство", score:9, evidence:"Публичный контакт по рекламе и владелец указаны в описании.", draft:"Здравствуйте. Для аудитории поставщиков предлагаю полезную рубрику: один разрешённый товар, текущий кадр и две гипотезы, что проверить первым. Без массового предложения услуг и без обещаний продаж. Подскажите, можно ли согласовать пилотный выпуск?" }
];

const comments = [
  ["marketplace","WB / Ozon","Показы есть, а кликов мало","Здесь я бы сначала смотрел не на всю карточку, а на главный кадр в маленькой выдаче. Сравните рядом 5–7 ближайших конкурентов: крупность, контраст, первый смысл. Если пришлёте артикул, подскажу, какую одну гипотезу проверить первой."],
  ["fashion","Fashion","Нужна новая съёмка коллекции","Перед полной съёмкой есть смысл проверить три роли: силуэт, движение и фактуру. Один товар в двух визуальных направлениях покажет, какой язык бренда стоит масштабировать. Если дадите одну модель и текущие материалы, предложу первый тест."],
  ["beauty","Beauty","Покупателю непонятен эффект","Я бы разделил обещание и доказательство. Сначала показать применение, фактуру и честный сценарий, не добавляя медицинского результата, которого нет в данных. Пришлите три частых вопроса покупателей — из них получится структура кадров."],
  ["home","Home","Не видно размер товара","Похоже, здесь не хватает ответа «как это будет у меня дома». Один кадр в интерьере, отдельная схема масштаба и макро материала решат разные сомнения лучше одной перегруженной инфографики."],
  ["cover","Обложка","Проект теряется в ленте","Обложку полезно проверять не полноэкранно, а в размере плеера или каталога. Я бы сделал три разных центральных образа и убрал всё, что не читается в маленьком квадрате."],
  ["d2c","D2C / сайт","Реклама и сайт выглядят разными брендами","После клика пользователь должен увидеть продолжение того же обещания: продукт, цвет, композицию и следующий шаг. Положите рекламный кадр рядом с hero сайта — разрыв обычно становится виден сразу."]
];

const barter = [
  ["Один SKU за публичный разбор","Небольшой бренд даёт разрешённые исходники и базовые данные. WISE / FRAME делает две гипотезы главного кадра. Публично показываются только согласованные материалы.","бренд / селлер","Не обещать победителя до теста"],
  ["Обложка за гостевой материал","Подкаст или медиа получает три направления обложки. В ответ — совместный пост о процессе и ссылка на бесплатную диагностику.","подкаст / медиа","Права на название и изображения фиксируются письменно"],
  ["Визуал для подборки","Покупательский канал выбирает один товар участника; WISE / FRAME готовит адаптацию под ленту и фиксирует критерий сравнения.","канал подборок","Не маскировать рекламу и соблюдать маркировку"],
  ["Creator‑тест 18+","Совершеннолетний автор с правами на свой образ получает три превью одной темы; WISE / FRAME может показать процесс после явного согласия.","стример / creator","Подтвердить 18+, согласие и границы использования"]
];

const todayTasks = [
  ["Проверить публичный URL Mini App","Текущий временный туннель не работает; не ставить его в новые посты."],
  ["Утвердить первые 3 поста","Манифест, fashion A/B и beauty‑воронка уже снабжены изображениями."],
  ["Открыть 3 контакта","Сверить дату, правила и актуальность контакта до копирования черновика."],
  ["Записать 2 ролика","День 1: эксперт в кадре и разбор экрана."],
  ["Собрать один SKU","Артикул, текущий кадр и одна доступная метрика."],
  ["Зафиксировать цифры","Просмотры 24/72 часа, ответы, запросы артикулов и квалифицированные диалоги."]
];

let reels = [];
let channel = [];
let activeLeadKind = "все";
let activeReelDay = 1;
let activePlanDay = 1;

document.querySelectorAll("[data-open]").forEach(button => button.addEventListener("click", () => openScreen(button.dataset.open)));
function openScreen(name) {
  document.querySelectorAll(".screen").forEach(screen => screen.classList.toggle("active", screen.dataset.screen === name));
  document.querySelectorAll("#side-nav [data-open]").forEach(button => button.classList.toggle("active", button.dataset.open === name));
  window.scrollTo({ top: 0, behavior: "smooth" });
}

function renderToday() {
  const saved = JSON.parse(localStorage.getItem("wiseReachToday") || "{}");
  const root = document.querySelector("#today-list");
  root.innerHTML = todayTasks.map((item,index)=>`<label class="today-task ${saved[index]?"done":""}"><input type="checkbox" data-task="${index}" ${saved[index]?"checked":""}><span>${String(index+1).padStart(2,"0")}</span><div><b>${item[0]}</b><p>${item[1]}</p></div></label>`).join("");
  const update = () => { const checked = [...root.querySelectorAll("input")].filter(input=>input.checked).length; document.querySelector("#today-progress").textContent=`${checked}/${todayTasks.length}`; };
  root.addEventListener("change", event => { const input=event.target.closest("input[data-task]"); if(!input)return; saved[input.dataset.task]=input.checked; localStorage.setItem("wiseReachToday",JSON.stringify(saved)); input.closest("label").classList.toggle("done",input.checked); update(); });
  update();
}

function renderLeads() {
  const kinds=["все",...new Set(contacts.map(item=>item.kind))];
  document.querySelector("#lead-filters").innerHTML=kinds.map(kind=>`<button class="${kind===activeLeadKind?"active":""}" type="button" data-lead-kind="${kind}">${kind}</button>`).join("");
  const visible=contacts.filter(item=>activeLeadKind==="все"||item.kind===activeLeadKind);
  document.querySelector("#lead-count").textContent=visible.length;
  const statuses=JSON.parse(localStorage.getItem("wiseReachStatuses")||"{}");
  document.querySelector("#lead-list").innerHTML=visible.map(item=>`<article class="lead-card"><header><div><span>${item.kind} · ${item.score}/15</span><h2>${item.name}</h2><a href="${item.url}" target="_blank" rel="noopener noreferrer">${item.handle} ↗</a></div><select data-status="${item.id}" aria-label="Статус контакта"><option ${!statuses[item.id]?"selected":""}>не открыт</option><option ${statuses[item.id]==="проверен"?"selected":""}>проверен</option><option ${statuses[item.id]==="черновик готов"?"selected":""}>черновик готов</option><option ${statuses[item.id]==="согласован"?"selected":""}>согласован</option><option ${statuses[item.id]==="стоп"?"selected":""}>стоп</option></select></header><div class="lead-grid"><p><small>Аудитория</small>${item.audience}</p><p><small>Почему подходит</small>${item.why}</p><p><small>Что предложить</small>${item.offer}</p><p><small>Формат</small>${item.format}</p></div><details><summary>Черновик обращения</summary><p>${item.draft}</p><button type="button" data-copy-text="${escapeAttr(item.draft)}">Копировать</button></details><footer>${item.evidence}</footer></article>`).join("");
}

function renderBarter(){document.querySelector("#barter-grid").innerHTML=barter.map((item,index)=>`<article><span>0${index+1} · ${item[2]}</span><h2>${item[0]}</h2><p>${item[1]}</p><footer>${item[3]}</footer></article>`).join("");}

function renderComments(id="marketplace"){
  const item=comments.find(value=>value[0]===id)||comments[0];
  document.querySelector("#comment-categories").innerHTML=comments.map(value=>`<button class="${value[0]===item[0]?"active":""}" type="button" data-comment="${value[0]}">${value[1]}</button>`).join("");
  document.querySelector("#comment-label").textContent=item[1]; document.querySelector("#comment-title").textContent=item[2]; document.querySelector("#comment-copy").textContent=item[3];
}

function renderReelDays(){document.querySelector("#reel-days").innerHTML=Array.from({length:30},(_,i)=>`<button class="${i+1===activeReelDay?"active":""}" type="button" data-reel-day="${i+1}">${i+1}</button>`).join(""); renderReels();}
function renderReels(){const items=reels.filter(item=>item.day===activeReelDay);document.querySelector("#reel-grid").innerHTML=items.map(item=>`<article><header><span>${item.date} · ${item.slot}</span><a href="${item.exampleUrl}" target="_blank" rel="noopener noreferrer">пример ↗</a></header><h2>${item.title}</h2><b>«${item.hook}»</b><p>${item.speech}</p><details><summary>Полный съёмочный лист</summary><ul>${item.shots.map(shot=>`<li>${shot}</li>`).join("")}</ul><p><small>Надписи</small>${item.overlays.join(" / ")}</p><p><small>Реквизит</small>${item.props}</p><p><small>Фон и одежда</small>${item.setting}</p><p><small>Звук</small>${item.audio}</p><p><small>Описание</small>${item.caption}</p><p><small>Адаптация</small>${item.adaptation}</p></details></article>`).join("");}

function renderPlanDays(){document.querySelector("#plan-days").innerHTML=Array.from({length:30},(_,i)=>`<button class="${i+1===activePlanDay?"active":""}" type="button" data-plan-day="${i+1}">${i+1}</button>`).join("");renderPlan();}
function renderPlan(){const items=channel.filter(item=>item.day===activePlanDay);document.querySelector("#plan-grid").innerHTML=items.map(item=>`<article><header><span>${item.time} · ${item.kind}</span><b>${item.title}</b></header><p>${item.text.replaceAll("**","")}</p><footer><span>${item.image}</span><button type="button" data-copy-text="${escapeAttr(item.text.replaceAll("**",""))}">Копировать пост</button></footer></article>`).join("");}

function updateMoney(){const data=new FormData(document.querySelector("#money-form"));const entry=Number(data.get("entry"))||0,core=Number(data.get("core"))||0,free=Number(data.get("free"))||0,entryRate=(Number(data.get("entryRate"))||0)/100,coreRate=(Number(data.get("coreRate"))||0)/100;const entryOrders=Math.floor(free*entryRate),coreOrders=Math.floor(entryOrders*coreRate),total=entryOrders*entry+coreOrders*core;document.querySelector("#money-total").textContent=new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB",maximumFractionDigits:0}).format(total);document.querySelector("#money-detail").textContent=`${free} диагностик → ${entryOrders} первых продуктов → ${coreOrders} основных услуг.`;}

document.addEventListener("click",async event=>{
  const leadFilter=event.target.closest("[data-lead-kind]");if(leadFilter){activeLeadKind=leadFilter.dataset.leadKind;renderLeads();return;}
  const comment=event.target.closest("[data-comment]");if(comment){renderComments(comment.dataset.comment);return;}
  const reelDay=event.target.closest("[data-reel-day]");if(reelDay){activeReelDay=Number(reelDay.dataset.reelDay);renderReelDays();return;}
  const planDay=event.target.closest("[data-plan-day]");if(planDay){activePlanDay=Number(planDay.dataset.planDay);renderPlanDays();return;}
  const copy=event.target.closest("[data-copy-text]");if(copy){await copyText(copy.dataset.copyText);showToast("Черновик скопирован");}
});
document.addEventListener("change",event=>{const select=event.target.closest("[data-status]");if(!select)return;const statuses=JSON.parse(localStorage.getItem("wiseReachStatuses")||"{}");statuses[select.dataset.status]=select.value;localStorage.setItem("wiseReachStatuses",JSON.stringify(statuses));showToast("Статус сохранён только на этом устройстве");});
document.querySelector("#copy-comment").addEventListener("click",async()=>{await copyText(document.querySelector("#comment-copy").textContent);showToast("Комментарий скопирован");});
document.querySelector("#money-form").addEventListener("input",updateMoney);

async function copyText(text){if(navigator.clipboard?.writeText){try{return await navigator.clipboard.writeText(text);}catch{}}const area=document.createElement("textarea");area.value=text;area.style.position="fixed";area.style.opacity="0";document.body.append(area);area.select();document.execCommand("copy");area.remove();}
function showToast(text){const toast=document.querySelector("#toast");toast.textContent=text;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1700);}
function escapeAttr(value){return String(value).replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;");}

async function boot(){renderToday();renderLeads();renderBarter();renderComments();updateMoney();try{[reels,channel]=await Promise.all([fetch("./data/reels-30-days.json").then(r=>r.json()),fetch("./data/channel-30-days.json").then(r=>r.json())]);renderReelDays();renderPlanDays();}catch(error){document.querySelector("#reel-grid").innerHTML=`<p class="notice">Не удалось загрузить сценарии: ${error.message}</p>`;document.querySelector("#plan-grid").innerHTML=`<p class="notice">Не удалось загрузить план: ${error.message}</p>`;}}
boot();
